# MNIST Classifier Model with Multiple Logistic Regression

## Import Libraries

In [127]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

## Define Functions

In [128]:
# One-hot Encoding for lables
def one_hot_encoding(labels, class_num):
    data_num = len(labels) # 60000, 10000
    result = np.zeros((data_num, 10))
    
    for idx in range(data_num):
        result[idx][labels[idx]] = 1
        
    return result

def Z(X, W, B):
    return tf.add(tf.matmul(X, W), B)

def softmax(Z):
    return tf.nn.softmax(Z)

def cross_entropy(Y, softmax):
    return -tf.reduce_sum(Y * tf.log(softmax), axis=1)

## Initialize Variables

In [129]:
# Load MNIST dataset from implementing Keras API
(x_train, y_train), (x_test, y_test) = mnist.load_data() # 60000 training set, 10000 testing set

print(f'x_train: {x_train.shape}')
print(f'y_train: {y_train.shape}')
print(f'x_test: {x_test.shape}')
print(f'y_test: {y_test.shape}')

x_train: (60000, 28, 28)
y_train: (60000,)
x_test: (10000, 28, 28)
y_test: (10000,)


## Preprocess Data

In [142]:
# Reshape train data and test data / Divide by 255 to normalize (the largest value of RGB is 255).
x_train = x_train.reshape((60000, 28*28)) / 255 # (60000, 784)
x_test = x_test.reshape((10000, 28*28)) / 255 # (10000, 784)

# Hyperparameters
class_num = 10
learning_rate = 0.001
batch_size = 100
batch_number = int(len(x_train) / batch_size)
epochs = 50

In [131]:
# Make Y values using One-Hot encoding
y_train = one_hot_encoding(y_train, class_num)
print(y_train[:4])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Build Model

In [143]:
# Initialize tensors with proper size and data type (float32)
X = tf.placeholder(tf.float32, [None, 28 * 28])
Y = tf.placeholder(tf.float32, [None, class_num])
W = tf.Variable(np.zeros((784, 10), np.float32))
B = tf.Variable(np.zeros((len(x_train), 10),np.float32))

In [133]:
softmax = softmax(Z(X, W, B))
cost = cross_entropy(Y, softmax)
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [144]:
with tf.Session() as sesh:
    sesh.run(tf.global_variables_initializer())
    
    for epoch in range(epochs):
        for i in range(batch_number):
            offset = i * epoch
            x = x_train[offset: offset + batch_size]
            y = y_train[offset: offset + batch_size]
            sesh.run(optimizer, feed_dict={X: x, Y:y})
            c = sesh.run(cost, feed_dict={X:x, Y:y})
        
        if not epoch % 2:
            print(f'epoch:{epoch:2d} cost={c:.4f}')
            
    correct_pred = tf.equal(tf.argmax(pred, 1), tf.argmax(Y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
    acc = accuracy.eval({X: x_test, Y: y_test})
    print(f'Accuracy: {acc * 100:.2f}%')

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_16' with dtype float and shape [60000,784]
	 [[node Placeholder_16 (defined at C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\framework\ops.py:1762) ]]

Original stack trace for 'Placeholder_16':
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\contextvars\__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\contextvars\__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\contextvars\__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel\kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\contextvars\__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\IPython\core\interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\IPython\core\interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\IPython\core\interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\IPython\core\interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-132-bbad3f105c8f>", line 2, in <module>
    X = tf.placeholder(tf.float32, [len(x_train), 28 * 28])
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 8038, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3371, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3440, in _create_op_internal
    op_def=op_def)
  File "C:\Users\KyochulJang\anaconda3\envs\dlstudy\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1762, in __init__
    self._traceback = tf_stack.extract_stack()
